/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h>
#include "nfs.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

void *
nfsproc3_null_3(CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, NFSPROC3_NULL, xdr_void, NULL, xdr_void, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	return ((void *)&clnt_res);
}

GETATTR3res *
nfsproc3_getattr_3(GETATTR3args arg1,  CLIENT *clnt)
{
	static GETATTR3res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, NFSPROC3_GETATTR, xdr_GETATTR3args, &arg1, xdr_GETATTR3res, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

SETATTR3res *
nfsproc3_setattr_3(SETATTR3args arg1,  CLIENT *clnt)
{
	static SETATTR3res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, NFSPROC3_SETATTR, xdr_SETATTR3args, &arg1, xdr_SETATTR3res, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

LOOKUP3res *
nfsproc3_lookup_3(LOOKUP3args arg1,  CLIENT *clnt)
{
	static LOOKUP3res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, NFSPROC3_LOOKUP, xdr_LOOKUP3args, &arg1, xdr_LOOKUP3res, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

ACCESS3res *
nfsproc3_access_3(ACCESS3args arg1,  CLIENT *clnt)
{
	static ACCESS3res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, NFSPROC3_ACCESS, xdr_ACCESS3args, &arg1, xdr_ACCESS3res, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

READLINK3res *
nfsproc3_readlink_3(READLINK3args arg1,  CLIENT *clnt)
{
	static READLINK3res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, NFSPROC3_READLINK, xdr_READLINK3args, &arg1, xdr_READLINK3res, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

READ3res *
nfsproc3_read_3(READ3args arg1,  CLIENT *clnt)
{
	static READ3res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, NFSPROC3_READ, xdr_READ3args, &arg1, xdr_READ3res, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

WRITE3res *
nfsproc3_write_3(WRITE3args arg1,  CLIENT *clnt)
{
	static WRITE3res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, NFSPROC3_WRITE, xdr_WRITE3args, &arg1, xdr_WRITE3res, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

CREATE3res *
nfsproc3_create_3(CREATE3args arg1,  CLIENT *clnt)
{
	static CREATE3res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, NFSPROC3_CREATE, xdr_CREATE3args, &arg1, xdr_CREATE3res, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

MKDIR3res *
nfsproc3_mkdir_3(MKDIR3args arg1,  CLIENT *clnt)
{
	static MKDIR3res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, NFSPROC3_MKDIR, xdr_MKDIR3args, &arg1, xdr_MKDIR3res, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

SYMLINK3res *
nfsproc3_symlink_3(SYMLINK3args arg1,  CLIENT *clnt)
{
	static SYMLINK3res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, NFSPROC3_SYMLINK, xdr_SYMLINK3args, &arg1, xdr_SYMLINK3res, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

MKNOD3res *
nfsproc3_mknod_3(MKNOD3args arg1,  CLIENT *clnt)
{
	static MKNOD3res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, NFSPROC3_MKNOD, xdr_MKNOD3args, &arg1, xdr_MKNOD3res, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

REMOVE3res *
nfsproc3_remove_3(REMOVE3args arg1,  CLIENT *clnt)
{
	static REMOVE3res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, NFSPROC3_REMOVE, xdr_REMOVE3args, &arg1, xdr_REMOVE3res, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

RMDIR3res *
nfsproc3_rmdir_3(RMDIR3args arg1,  CLIENT *clnt)
{
	static RMDIR3res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, NFSPROC3_RMDIR, xdr_RMDIR3args, &arg1, xdr_RMDIR3res, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

RENAME3res *
nfsproc3_rename_3(RENAME3args arg1,  CLIENT *clnt)
{
	static RENAME3res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, NFSPROC3_RENAME, xdr_RENAME3args, &arg1, xdr_RENAME3res, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

LINK3res *
nfsproc3_link_3(LINK3args arg1,  CLIENT *clnt)
{
	static LINK3res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, NFSPROC3_LINK, xdr_LINK3args, &arg1, xdr_LINK3res, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

READDIR3res *
nfsproc3_readdir_3(READDIR3args arg1,  CLIENT *clnt)
{
	static READDIR3res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, NFSPROC3_READDIR, xdr_READDIR3args, &arg1, xdr_READDIR3res, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

READDIRPLUS3res *
nfsproc3_readdirplus_3(READDIRPLUS3args arg1,  CLIENT *clnt)
{
	static READDIRPLUS3res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, NFSPROC3_READDIRPLUS, xdr_READDIRPLUS3args, &arg1, xdr_READDIRPLUS3res, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

FSSTAT3res *
nfsproc3_fsstat_3(FSSTAT3args arg1,  CLIENT *clnt)
{
	static FSSTAT3res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, NFSPROC3_FSSTAT, xdr_FSSTAT3args, &arg1, xdr_FSSTAT3res, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

FSINFO3res *
nfsproc3_fsinfo_3(FSINFO3args arg1,  CLIENT *clnt)
{
	static FSINFO3res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, NFSPROC3_FSINFO, xdr_FSINFO3args, &arg1, xdr_FSINFO3res, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

PATHCONF3res *
nfsproc3_pathconf_3(PATHCONF3args arg1,  CLIENT *clnt)
{
	static PATHCONF3res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, NFSPROC3_PATHCONF, xdr_PATHCONF3args, &arg1, xdr_PATHCONF3res, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

COMMIT3res *
nfsproc3_commit_3(COMMIT3args arg1,  CLIENT *clnt)
{
	static COMMIT3res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, NFSPROC3_COMMIT, xdr_COMMIT3args, &arg1, xdr_COMMIT3res, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}
